### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by johnnyshields** [gmailgem/gmail#105]
_From @webcracy on April 21, 2014 19:29_

# Suggested Roadmap

Here's a proposal to organise ourselves to deal with open PR's. Please share your  thoughts.

Could contributors start tagging issues as well? That would be awesome. Cc: @nu7hatch, @jgrevich , @johnnyshields.

Meanwhile I'll edit this post according to further suggestions, votes and ideas.

## ~~v0.4.1 - Fix fresh installs~~
* [x] MIME dependency fix (#109)
* [x] gitignore Gemfile.lock (#100)
* [x] cherry-pick 8fc82e8 from (#66)
* [x] Get all tests passing in 1.8.7

## v0.5.0 - Return of the Jedi
* [x] Last version compatible with ~~Ruby 1.8.7~~ and 1.9.3
* [x] Add Ruby 2.X support 
* [x] Ruby 1.9.3 IMAP Extensions fix (use #66, provided it's patched as per the comments)
* [x] XOAuth 2 support (use #80, make sure the change in `account.yml` for testing is explained in 
README)
* [x] Localised labels, better character support (use #83 and #82) -> #110
* [x] Better test coverage (use #75, #102 and #103)
* [x] Fix label addition/removal (in #102)
* [x] Investigate other issues and pull requests referenced in #96 

## v0.6.0 - A New Hope
* [ ] `#idle` command support (start with #93)
* [ ] Drop Ruby 1.x support
* [ ] Other stuff...

_Copied from original issue: nu7hatch/gmail#105_

**Comment by johnnyshields** [comment]
_From @jgrevich on April 21, 2014 21:31_

This is awesome! Great work @webcracy .  I'm going to focus on better test coverage and Ruby 2 support.  @johnnyshields is also going to help in this area: #103

**Comment by johnnyshields** [comment]
_From @webcracy on April 22, 2014 13:28_

Great, just added #103 to the list!

**Comment by johnnyshields** [comment]
I'm always glad to help. @jgrevich since you have access to commit can you start merging in some of these PRs?

**Comment by johnnyshields** [comment]
_From @jgrevich on April 23, 2014 1:12_

@johnnyshields of course.  Can you also help with the QA and add a comment to any PRs that have already been QAd (make sure PRs function as expected and make sure they have good test coverage that also handles edge cases).

**Comment by johnnyshields** [comment]
I'm using #62, #66, and #102 in production now. We should start with merging these.

**Comment by johnnyshields** [comment]
_From @jgrevich on April 23, 2014 1:49_

@johnnyshields Perfect, thank you. I'll merge those right now.

**Comment by johnnyshields** [comment]
_From @webcracy on April 23, 2014 9:19_

@jgrevich @johnnyshields Please note that #102 and #66 are not ready for merging IMO. 

#66 breaks my production systems and I'm sure will break many use cases (cf my comment there, and my pull request to @dcu), and I can safely say that parts of #102 are actually under development (cf. my contributions :P ).

Can't say for #62, didn't test it yet (am on #75 ATM)

**Comment by johnnyshields** [comment]
_From @webcracy on April 24, 2014 17:51_

@johnnyshields @jgrevich  Do you agree with this roadmap for version support, or do you have other suggestions?

To be clear, in this scenario we support 1.8.7, 1.9.2 and 1.9.3 in 0.4.1 and drop them in 0.5.0, where only Ruby 2 is supported. 

This means that all PR's and Issues are first integrated with 1.8.7, 1.9.2 and 1.9.3 compatibility. When done, we release 0.4.1 (hopefully @nu7hatch will be op by the time we're ready; otherwise we just tag it). Then we move into 0.5.0 where we add 2.0 support and whatever else makes the list.

**Comment by johnnyshields** [comment]
@webcracy I think version 0.4.1 should only have #102 because its critical (i.e. the gem is broken in it's current state, unless we remove `require 'mime/message'` from `lib/gmail/message.rb`

I'd suggest we move all the rest to 0.5.0, so as to spend minimal time thinking about Ruby 1.8.7.

**Comment by johnnyshields** [comment]
@jcarbo @webcracy @jgrevich @bootstraponline any thoughts on what remains before we can push 0.5.0?

**Comment by bootstraponline** [comment]
I think we're ready? For anyone on Ruby 2+, the current release is broken.

**Comment by johnnyshields** [comment]
@jcarbo your thoughts?

**Comment by jcarbo** [comment]
I'm on board :shipit:

**Comment by johnnyshields** [comment]
Cool, will tag and release in next 24 hours. I'm going to close this issue for now as it's core objective, i.e. stabilizing and moving forward with this project, has been achieved.  Awesome work everybody :tada:

**Comment by bootstraponline** [comment]
It looks like I'm not a gem owner so another dev has to release. It'll be great to see 0.5.0 on rubygems. :shipit:
