### ISSUE TITLE
Treasure Hunt - Pull in branches

### ISSUE THREAD

**Issue by johnnyshields** [gmailgem/gmail#139]
Due to poor maintenance of this gem over the past ~4 years there have been many forks (186 as of time of writing). Most of these are noise, i.e. people fixing the same issue again and again. However some contain viable features. We should investigate these branches for goodies that can be merged into master. I've done a scan and have found the following branches which may have useful changes:
## TODO
- [ ] [drowningcat/gmail](https://github.com/drowningcat/gmail)
- [ ] [humanbagel/gmail](https://github.com/humanbagel/gmail)
- [ ] [orospakr/gmail](https://github.com/orospakr/gmail) # integrate_celluloid_net_imap_2
- [ ] [liquidautumn/gmail](https://github.com/liquidautumn/gmail)
- [ ] [mattparmett/gmail](https://github.com/mattparmett/gmail)
- [ ] [ynnadrules/gmail](https://github.com/ynnadrules/gmail)
- [ ] [Yesware/gmail](https://github.com/Yesware/gmail)
## Done
- [x] :white_check_mark: **[jamescallmebrent/gmail](https://github.com/jamescallmebrent/gmail) Used some piece for #149**  - jcarbo
- [x] :white_check_mark: **[stefanobernardi/gmail](https://github.com/stefanobernardi/gmail) Used some piece for #147** - jcarbo
- [x] ~~[pricematch/gmail](https://github.com/pricematch/gmail) # fix_delete_method~~ - jcarbo 
- [x] ~~[pricematch/gmail](https://github.com/pricematch/gmail) # master~~ - jcarbo 
- [x] ~~[314Technologies/gmail](https://github.com/314Technologies/gmail)~~ - jcarbo
- [x] ~~[vu0tran/gmail](https://github.com/vu0tran/gmail)~~ - jcarbo
- [x] ~~[maccman/gmail](https://github.com/maccman/gmail)~~ - jcarbo
- [x] ~~[zxuwen/gmail](https://github.com/zxuwen/gmail)~~ - jcarbo
- [x] ~~[stuartchaney/gmail](https://github.com/stuartchaney/gmail)~~ - jcarbo
- [x] ~~[arp/gmail](https://github.com/arp/gmail)~~ - jcarbo
- [x] ~~[wiro34/gmail](https://github.com/wiro34/gmail)~~ - jcarbo
- [x] ~~[sherm8n/gmail](https://github.com/sherm8n/gmail)~~ - jcarbo
- [x] ~~[darrhiggs/gmail](https://github.com/darrhiggs/gmail)~~ - jcarbo
- [x] ~~[selvan/gmail](https://github.com/selvan/gmail)~~ - jcarbo
- [x] ~~[mcls/gmail](https://github.com/mcls/gmail)~~ - jcarbo
- [x] ~~[dcu/gmail](https://github.com/dcu/gmail)~~ - jcarbo
- [x] ~~[scarow/gmail](https://github.com/scarow/gmail)~~ - jcarbo
- [x] ~~[ynnadrules/gmail](https://github.com/ynnadrules/gmail)~~ - jcarbo
- [x] ~~[mymex1/gmail](https://github.com/mymex1/gmail)~~ - jcarbo
- [x] ~~[synth/gmail](https://github.com/synth/gmail)~~ - jcarbo
- [x] ~~[larrylv/gmail](https://github.com/larrylv/gmail)~~ - jcarbo
- [x] ~~[kaspth/gmail](https://github.com/kaspth/gmail)~~ - jcarbo
- [x] ~~[lowang/gmail](https://github.com/lowang/gmail)~~ - jcarbo
- [x] ~~[tmesquita/gmail](https://github.com/tmesquita/gmail)~~ - jcarbo

**Comment by johnnyshields** [comment]
As of version 0.7.0 (Aug 19, 2018) this gem is officially deprecated and will no longer be maintained. Please instead use Google's official Gmail API Ruby Client, which uses the Gmail API rather than IMAP and has significantly better performance and reliability.
